version: "3.9"
services:
  backend:
    env_file:
    - .env
    build: .
    ports:
      - "8000:3001"
  frontend:
    env_file:
      - frontend/.env.local
    build: frontend/
    ports:
      - "3000:3000"
    

  